
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/manoj/miniconda3/bin/"
      - "/home/manoj/miniconda3/condabin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/java8path/"
      - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath/"
      - "/mnt/c/WINDOWS/system32/"
      - "/mnt/c/WINDOWS/"
      - "/mnt/c/WINDOWS/System32/Wbem/"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/WINDOWS/System32/OpenSSH/"
      - "/mnt/c/Program Files/dotnet/"
      - "/mnt/c/Program Files/Git/cmd/"
      - "/mnt/c/ProgramData/chocolatey/bin/"
      - "/mnt/c/Program Files/Microsoft SQL Server/170/Tools/Binn/"
      - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "/mnt/c/Program Files/Git LFS/"
      - "/mnt/c/Program Files/nodejs/"
      - "/mnt/c/Program Files/LLVM/bin/"
      - "/mnt/c/Program Files/CMake/bin/"
      - "/mnt/c/Program Files/GitHub CLI/"
      - "/mnt/c/Users/manoj/AppData/Local/Programs/Python/Python313/Scripts/"
      - "/mnt/c/Users/manoj/.local/bin/claude.exe/"
      - "/mnt/c/Users/manoj/AppData/Local/Programs/Python/Python313/"
      - "/mnt/c/Users/manoj/bin/"
      - "/mnt/c/Program Files/Calibre2/"
      - "/mnt/c/msys64/mingw64/bin/"
      - "/mnt/c/Users/manoj/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "/mnt/c/Users/manoj/AppData/Roaming/npm/"
      - "/mnt/c/Users/manoj/.local/bin/"
      - "/snap/bin/"
    searched_directories:
      - "/home/manoj/miniconda3/bin/uname"
      - "/home/manoj/miniconda3/condabin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/manoj/miniconda3/bin"
        - "/home/manoj/miniconda3/condabin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/java8path"
        - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0"
        - "/mnt/c/WINDOWS/System32/OpenSSH"
        - "/mnt/c/Program Files/dotnet"
        - "/mnt/c/Program Files/Git/cmd"
        - "/mnt/c/ProgramData/chocolatey/bin"
        - "/mnt/c/Program Files/Microsoft SQL Server/170/Tools/Binn"
        - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit"
        - "/mnt/c/Program Files/Git LFS"
        - "/mnt/c/Program Files/nodejs"
        - "/mnt/c/Program Files/LLVM/bin"
        - "/mnt/c/Program Files/CMake/bin"
        - "/mnt/c/Program Files/GitHub CLI"
        - "/mnt/c/Users/manoj/AppData/Local/Programs/Python/Python313/Scripts"
        - "/mnt/c/Users/manoj/.local/bin/claude.exe"
        - "/mnt/c/Users/manoj/AppData/Local/Programs/Python/Python313"
        - "/mnt/c/Users/manoj/bin"
        - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/java8path"
        - "/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0"
        - "/mnt/c/WINDOWS/System32/OpenSSH"
        - "/mnt/c/Program Files/dotnet"
        - "/mnt/c/Program Files/Git/cmd"
        - "/mnt/c/ProgramData/chocolatey/bin"
        - "/mnt/c/Program Files/Microsoft SQL Server/170/Tools/Binn"
        - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit"
        - "/mnt/c/Program Files/Git LFS"
        - "/mnt/c/Program Files/Calibre2"
        - "/mnt/c/Program Files/nodejs"
        - "/mnt/c/msys64/mingw64/bin"
        - "/mnt/c/Users/manoj/AppData/Local/Programs/Microsoft VS Code/bin"
        - "/mnt/c/Users/manoj/AppData/Roaming/npm"
        - "/mnt/c/msys64/mingw64/bin"
        - "/mnt/c/Users/manoj/AppData/Local/Programs/Microsoft VS Code/bin"
        - "/mnt/c/Users/manoj/AppData/Roaming/npm"
        - "/mnt/c/Users/manoj/.local/bin"
        - "/snap/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.114.1-microsoft-standard-WSL2 - x86_64
...
